# prueba 1
class Calculadora:
    def valor(self):
        #fuerzo el error
        return 2